[package]
name = "sp1-ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "sp1_ffi"
crate-type = ["cdylib"]

[dependencies]
fibonacci-script = { workspace = true }
bincode = "1.3.3"
libc = "0.2"
