use sp1_prover::types::{SP1ProvingKey, SP1VerifyingKey};
use sp1_sdk::{ProverClient, SP1Stdin};

use crate::ProveArgs;

/// The ELF (executable and linkable format) file for the Succinct RISC-V zkVM.
///
/// This file is generated by running `cargo prove build` inside the `program` directory.
pub const FIBONACCI_ELF: &[u8] = include_bytes!("../../../program/elf/riscv32im-succinct-zkvm-elf");

pub fn init_client(args: ProveArgs) -> (ProverClient, SP1Stdin, SP1ProvingKey, SP1VerifyingKey) {
    let client = ProverClient::new();
    let (pk, vk) = client.setup(FIBONACCI_ELF);
    let mut stdin = SP1Stdin::new();
    stdin.write(&args.n);
    
    (client, stdin, pk, vk)
}
